const quizData = [
  {
    question: "What is the capital of France?",
    options: ["Berlin", "Madrid", "Paris", "Rome"],
    correctAnswer: "Paris",
    difficulty: "easy",
    category: "history",
  },
  {
    question: "Which programming language is known as the language of the web?",
    options: ["Python", "JavaScript", "C++", "Java"],
    correctAnswer: "JavaScript",
    difficulty: "intermediate",
    category: "technology",
  },
  {
    question: "What is the largest planet in our solar system?",
    options: ["Earth", "Jupiter", "Saturn", "Mars"],
    correctAnswer: "Jupiter",
    difficulty: "easy",
    category: "science",
  },
  {
    question: "Which country is known as the Land of the Rising Sun?",
    options: ["India", "Australia", "Japan", "South Korea"],
    correctAnswer: "Japan",
    difficulty: "easy",
    category: "geography",
  },
  {
    question: "What is the chemical symbol for water?",
    options: ["H2O", "O2", "CO2", "NaCl"],
    correctAnswer: "H2O",
    difficulty: "easy",
    category: "science",
  },
  //Math
  {
    question: "What is 5 + 3?",
    options: ["6", "7", "8", "9"],
    correctAnswer: "8",
    difficulty: "easy",
    category: "math",
  },
  {
    question: "What is the square root of 64?",
    options: ["6", "7", "8", "9"],
    correctAnswer: "8",
    difficulty: "easy",
    category: "math",
  },
  {
    question: "What is the value of π (pi) to two decimal places?",
    options: ["3.12", "3.14", "3.16", "3.18"],
    correctAnswer: "3.14",
    difficulty: "easy",
    category: "math",
  },
  {
    question: "What is the sum of the angles in a triangle?",
    options: ["180 degrees", "360 degrees", "90 degrees", "270 degrees"],
    correctAnswer: "180 degrees",
    difficulty: "easy",
    category: "math",
  },
  {
    question:
      "What is the value of the golden ratio (φ) to two decimal places?",
    options: ["1.61", "1.62", "1.63", "1.64"],
    correctAnswer: "1.62",
    difficulty: "intermediate",
    category: "math",
  },
  {
    question: "What is the area of a circle with radius 5?",
    options: ["25π", "10π", "20π", "5π"],
    correctAnswer: "25π",
    difficulty: "intermediate",
    category: "math",
  },
  {
    question: "What is the value of 7 factorial (7!)?",
    options: ["5040", "720", "120", "40320"],
    correctAnswer: "5040",
    difficulty: "intermediate",
    category: "math",
  },
  {
    question: "What is the Pythagorean theorem?",
    options: [
      "a^2 + b^2 = c^2",
      "a^2 - b^2 = c^2",
      "a^2 + b = c^2",
      "a + b^2 = c^2",
    ],
    correctAnswer: "a^2 + b^2 = c^2",
    difficulty: "easy",
    category: "math",
  },
  {
    question: "What is the value of the square root of 144?",
    options: ["10", "11", "12", "13"],
    correctAnswer: "12",
    difficulty: "easy",
    category: "math",
  },
  {
    question: "What is the sum of the first 10 natural numbers?",
    options: ["45", "50", "55", "60"],
    correctAnswer: "55",
    difficulty: "easy",
    category: "math",
  },
  {
    question: "What is the value of e (Euler's number) to two decimal places?",
    options: ["2.71", "2.72", "2.73", "2.74"],
    correctAnswer: "2.72",
    difficulty: "intermediate",
    category: "math",
  },
  {
    question: "What is the value of log(100) to the base 10?",
    options: ["1", "2", "3", "4"],
    correctAnswer: "2",
    difficulty: "intermediate",
    category: "math",
  },
  {
    question: "What is the value of sin(90 degrees)?",
    options: ["0", "0.5", "1", "undefined"],
    correctAnswer: "1",
    difficulty: "easy",
    category: "math",
  },
  {
    question: "What is the value of cos(0 degrees)?",
    options: ["0", "0.5", "1", "undefined"],
    correctAnswer: "1",
    difficulty: "easy",
    category: "math",
  },
  {
    question: "What is the value of tan(45 degrees)?",
    options: ["0", "1", "undefined", "infinity"],
    correctAnswer: "1",
    difficulty: "easy",
    category: "math",
  },
  {
    question: "What is the value of the integral of x dx?",
    options: ["x^2/2 + C", "x^2 + C", "2x + C", "x + C"],
    correctAnswer: "x^2/2 + C",
    difficulty: "intermediate",
    category: "math",
  },
  {
    question: "What is the value of the derivative of sin(x)?",
    options: ["cos(x)", "-cos(x)", "sin(x)", "-sin(x)"],
    correctAnswer: "cos(x)",
    difficulty: "intermediate",
    category: "math",
  },
  {
    question: "What is the value of the derivative of cos(x)?",
    options: ["sin(x)", "-sin(x)", "cos(x)", "-cos(x)"],
    correctAnswer: "-sin(x)",
    difficulty: "intermediate",
    category: "math",
  },
  {
    question: "What is the value of the derivative of tan(x)?",
    options: ["sec^2(x)", "-sec^2(x)", "tan(x)", "-tan(x)"],
    correctAnswer: "sec^2(x)",
    difficulty: "intermediate",
    category: "math",
  },
  {
    question: "What is the value of the integral of 1/x dx?",
    options: ["ln|x| + C", "1/x + C", "x + C", "ln(x) + C"],
    correctAnswer: "ln|x| + C",
    difficulty: "intermediate",
    category: "math",
  },
  {
    question: "What is the value of the integral of e^x dx?",
    options: ["e^x + C", "x + C", "1/x + C", "ln(x) + C"],
    correctAnswer: "e^x + C",
    difficulty: "intermediate",
    category: "math",
  },
  {
    question: "What is the value of the integral of sin(x) dx?",
    options: ["-cos(x) + C", "cos(x) + C", "sin(x) + C", "-sin(x) + C"],
    correctAnswer: "-cos(x) + C",
    difficulty: "intermediate",
    category: "math",
  },
  {
    question: "What is the value of the integral of cos(x) dx?",
    options: ["sin(x) + C", "-sin(x) + C", "cos(x) + C", "-cos(x) + C"],
    correctAnswer: "sin(x) + C",
    difficulty: "intermediate",
    category: "math",
  },
  {
    question: "What is the value of the integral of tan(x) dx?",
    options: ["-ln|cos(x)| + C", "ln|cos(x)| + C", "tan(x) + C", "-tan(x) + C"],
    correctAnswer: "-ln|cos(x)| + C",
    difficulty: "intermediate",
    category: "math",
  },
  {
    question: "What is the value of the integral of sec(x) dx?",
    options: [
      "ln|sec(x) + tan(x)| + C",
      "-ln|sec(x) + tan(x)| + C",
      "sec(x) + C",
      "-sec(x) + C",
    ],
    correctAnswer: "ln|sec(x) + tan(x)| + C",
    difficulty: "intermediate",
    category: "math",
  },
  {
    question: "What is the value of the integral of csc(x) dx?",
    options: [
      "-ln|csc(x) + cot(x)| + C",
      "ln|csc(x) + cot(x)| + C",
      "csc(x) + C",
      "-csc(x) + C",
    ],
    correctAnswer: "-ln|csc(x) + cot(x)| + C",
    difficulty: "intermediate",
    category: "math",
  },
  {
    question: "What is the value of the integral of cot(x) dx?",
    options: ["ln|sin(x)| + C", "-ln|sin(x)| + C", "cot(x) + C", "-cot(x) + C"],
    correctAnswer: "ln|sin(x)| + C",
    difficulty: "intermediate",
    category: "math",
  },
  {
    question: "What is the value of the integral of sec^2(x) dx?",
    options: ["tan(x) + C", "-tan(x) + C", "sec(x) + C", "-sec(x) + C"],
    correctAnswer: "tan(x) + C",
    difficulty: "intermediate",
    category: "math",
  },
  {
    question: "What is the value of the integral of csc^2(x) dx?",
    options: ["-cot(x) + C", "cot(x) + C", "csc(x) + C", "-csc(x) + C"],
    correctAnswer: "-cot(x) + C",
    difficulty: "intermediate",
    category: "math",
  },
  // English
  {
    question: "What is the synonym of 'happy'?",
    options: ["Sad", "Joyful", "Angry", "Tired"],
    correctAnswer: "Joyful",
    difficulty: "easy",
    category: "english",
  },
  {
    question: "What is the antonym of 'big'?",
    options: ["Large", "Huge", "Small", "Gigantic"],
    correctAnswer: "Small",
    difficulty: "easy",
    category: "english",
  },
  {
    question: "What is the past tense of 'run'?",
    options: ["Running", "Ran", "Runs", "Runned"],
    correctAnswer: "Ran",
    difficulty: "easy",
    category: "english",
  },
  {
    question: "What is the plural form of 'child'?",
    options: ["Childs", "Children", "Childes", "Child"],
    correctAnswer: "Children",
    difficulty: "easy",
    category: "english",
  },
  {
    question: "What is the comparative form of 'good'?",
    options: ["Gooder", "Better", "Best", "More good"],
    correctAnswer: "Better",
    difficulty: "easy",
    category: "english",
  },
  {
    question: "What is the superlative form of 'bad'?",
    options: ["Badder", "Worse", "Worst", "Most bad"],
    correctAnswer: "Worst",
    difficulty: "easy",
    category: "english",
  },
  {
    question: "What is the synonym of 'quick'?",
    options: ["Slow", "Fast", "Lazy", "Calm"],
    correctAnswer: "Fast",
    difficulty: "easy",
    category: "english",
  },
  {
    question: "What is the antonym of 'hot'?",
    options: ["Warm", "Cold", "Cool", "Boiling"],
    correctAnswer: "Cold",
    difficulty: "easy",
    category: "english",
  },
  {
    question: "What is the past tense of 'eat'?",
    options: ["Eats", "Eating", "Ate", "Eaten"],
    correctAnswer: "Ate",
    difficulty: "easy",
    category: "english",
  },
  {
    question: "What is the plural form of 'mouse'?",
    options: ["Mouses", "Mice", "Mouse", "Mices"],
    correctAnswer: "Mice",
    difficulty: "easy",
    category: "english",
  },
  {
    question: "What is the synonym of 'intelligent'?",
    options: ["Dumb", "Smart", "Foolish", "Ignorant"],
    correctAnswer: "Smart",
    difficulty: "easy",
    category: "english",
  },
  {
    question: "What is the antonym of 'early'?",
    options: ["Late", "Soon", "Prompt", "Timely"],
    correctAnswer: "Late",
    difficulty: "easy",
    category: "english",
  },
  {
    question: "What is the past tense of 'go'?",
    options: ["Goes", "Going", "Went", "Gone"],
    correctAnswer: "Went",
    difficulty: "easy",
    category: "english",
  },
  {
    question: "What is the plural form of 'foot'?",
    options: ["Foots", "Feet", "Foot", "Feets"],
    correctAnswer: "Feet",
    difficulty: "easy",
    category: "english",
  },
  {
    question: "What is the synonym of 'beautiful'?",
    options: ["Ugly", "Pretty", "Plain", "Dull"],
    correctAnswer: "Pretty",
    difficulty: "easy",
    category: "english",
  },
  {
    question: "What is the antonym of 'strong'?",
    options: ["Weak", "Powerful", "Sturdy", "Robust"],
    correctAnswer: "Weak",
    difficulty: "easy",
    category: "english",
  },
  {
    question: "What is the past tense of 'see'?",
    options: ["Sees", "Seeing", "Saw", "Seen"],
    correctAnswer: "Saw",
    difficulty: "easy",
    category: "english",
  },
  {
    question: "What is the plural form of 'tooth'?",
    options: ["Tooths", "Teeth", "Tooth", "Teeths"],
    correctAnswer: "Teeth",
    difficulty: "easy",
    category: "english",
  },
  {
    question: "What is the synonym of 'angry'?",
    options: ["Happy", "Calm", "Furious", "Joyful"],
    correctAnswer: "Furious",
    difficulty: "easy",
    category: "english",
  },
  {
    question: "What is the antonym of 'light'?",
    options: ["Heavy", "Bright", "Dim", "Dark"],
    correctAnswer: "Heavy",
    difficulty: "easy",
    category: "english",
  },
  {
    question: "What is the past tense of 'write'?",
    options: ["Writes", "Writing", "Wrote", "Written"],
    correctAnswer: "Wrote",
    difficulty: "easy",
    category: "english",
  },
  {
    question: "What is the plural form of 'person'?",
    options: ["Persons", "People", "Person", "Peoples"],
    correctAnswer: "People",
    difficulty: "easy",
    category: "english",
  },
  {
    question: "What is the synonym of 'difficult'?",
    options: ["Easy", "Hard", "Simple", "Effortless"],
    correctAnswer: "Hard",
    difficulty: "easy",
    category: "english",
  },
  {
    question: "What is the antonym of 'rich'?",
    options: ["Wealthy", "Poor", "Affluent", "Prosperous"],
    correctAnswer: "Poor",
    difficulty: "easy",
    category: "english",
  },
  {
    question: "What is the past tense of 'drink'?",
    options: ["Drinks", "Drinking", "Drank", "Drunk"],
    correctAnswer: "Drank",
    difficulty: "easy",
    category: "english",
  },
  {
    question: "What is the plural form of 'fish'?",
    options: ["Fishes", "Fish", "Fishs", "Fishies"],
    correctAnswer: "Fish",
    difficulty: "easy",
    category: "english",
  },
  {
    question: "What is the synonym of 'happy'?",
    options: ["Sad", "Joyful", "Angry", "Tired"],
    correctAnswer: "Joyful",
    difficulty: "easy",
    category: "english",
  },
  {
    question: "What is the antonym of 'big'?",
    options: ["Large", "Huge", "Small", "Gigantic"],
    correctAnswer: "Small",
    difficulty: "easy",
    category: "english",
  },
  {
    question: "What is the past tense of 'run'?",
    options: ["Running", "Ran", "Runs", "Runned"],
    correctAnswer: "Ran",
    difficulty: "easy",
    category: "english",
  },
  {
    question: "What is the plural form of 'child'?",
    options: ["Childs", "Children", "Childes", "Child"],
    correctAnswer: "Children",
    difficulty: "easy",
    category: "english",
  },
  {
    question: "What is the comparative form of 'good'?",
    options: ["Gooder", "Better", "Best", "More good"],
    correctAnswer: "Better",
    difficulty: "easy",
    category: "english",
  },
  {
    question: "What is the superlative form of 'bad'?",
    options: ["Badder", "Worse", "Worst", "Most bad"],
    correctAnswer: "Worst",
    difficulty: "easy",
    category: "english",
  },
  {
    question: "What is the synonym of 'quick'?",
    options: ["Slow", "Fast", "Lazy", "Calm"],
    correctAnswer: "Fast",
    difficulty: "easy",
    category: "english",
  },
  {
    question: "What is the antonym of 'hot'?",
    options: ["Warm", "Cold", "Cool", "Boiling"],
    correctAnswer: "Cold",
    difficulty: "easy",
    category: "english",
  },
  {
    question: "What is the past tense of 'eat'?",
    options: ["Eats", "Eating", "Ate", "Eaten"],
    correctAnswer: "Ate",
    difficulty: "easy",
    category: "english",
  },
  {
    question: "What is the plural form of 'mouse'?",
    options: ["Mouses", "Mice", "Mouse", "Mices"],
    correctAnswer: "Mice",
    difficulty: "easy",
    category: "english",
  },
  {
    question: "What is the synonym of 'intelligent'?",
    options: ["Dumb", "Smart", "Foolish", "Ignorant"],
    correctAnswer: "Smart",
    difficulty: "easy",
    category: "english",
  },
  // History
  {
    question: "What is the capital of France?",
    options: ["Berlin", "Madrid", "Paris", "Rome"],
    correctAnswer: "Paris",
    difficulty: "easy",
    category: "history",
  },
  {
    question: "Who was the first President of the United States?",
    options: [
      "Thomas Jefferson",
      "Abraham Lincoln",
      "George Washington",
      "John Adams",
    ],
    correctAnswer: "George Washington",
    difficulty: "easy",
    category: "history",
  },
  {
    question: "In which year did World War II end?",
    options: ["1942", "1945", "1948", "1950"],
    correctAnswer: "1945",
    difficulty: "easy",
    category: "history",
  },
  {
    question: "Who discovered America?",
    options: [
      "Christopher Columbus",
      "Leif Erikson",
      "Ferdinand Magellan",
      "Marco Polo",
    ],
    correctAnswer: "Christopher Columbus",
    difficulty: "easy",
    category: "history",
  },
  {
    question:
      "What was the name of the ship that brought the Pilgrims to America in 1620?",
    options: ["Mayflower", "Santa Maria", "Pinta", "Nina"],
    correctAnswer: "Mayflower",
    difficulty: "easy",
    category: "history",
  },
  {
    question: "Who was the first Emperor of Rome?",
    options: ["Julius Caesar", "Augustus", "Nero", "Caligula"],
    correctAnswer: "Augustus",
    difficulty: "easy",
    category: "history",
  },
  {
    question: "What was the main cause of the American Civil War?",
    options: ["Slavery", "Taxation", "Territorial Expansion", "Trade Disputes"],
    correctAnswer: "Slavery",
    difficulty: "easy",
    category: "history",
  },
  {
    question: "Who was the British Prime Minister during World War II?",
    options: [
      "Winston Churchill",
      "Neville Chamberlain",
      "Clement Attlee",
      "Harold Macmillan",
    ],
    correctAnswer: "Winston Churchill",
    difficulty: "easy",
    category: "history",
  },
  {
    question:
      "What was the name of the first manned mission to land on the moon?",
    options: ["Apollo 11", "Apollo 12", "Apollo 13", "Apollo 14"],
    correctAnswer: "Apollo 11",
    difficulty: "easy",
    category: "history",
  },
  {
    question: "Who was the first female Prime Minister of the United Kingdom?",
    options: [
      "Margaret Thatcher",
      "Theresa May",
      "Angela Merkel",
      "Indira Gandhi",
    ],
    correctAnswer: "Margaret Thatcher",
    difficulty: "easy",
    category: "history",
  },
  {
    question: "In which year did the Berlin Wall fall?",
    options: ["1987", "1988", "1989", "1990"],
    correctAnswer: "1989",
    difficulty: "easy",
    category: "history",
  },
  {
    question:
      "Who was the leader of the Soviet Union during the Cuban Missile Crisis?",
    options: [
      "Joseph Stalin",
      "Nikita Khrushchev",
      "Leonid Brezhnev",
      "Mikhail Gorbachev",
    ],
    correctAnswer: "Nikita Khrushchev",
    difficulty: "intermediate",
    category: "history",
  },
  {
    question: "What was the name of the treaty that ended World War I?",
    options: [
      "Treaty of Versailles",
      "Treaty of Paris",
      "Treaty of Tordesillas",
      "Treaty of Ghent",
    ],
    correctAnswer: "Treaty of Versailles",
    difficulty: "intermediate",
    category: "history",
  },
  {
    question:
      "Who was the first President of the United States to be impeached?",
    options: [
      "Andrew Johnson",
      "Richard Nixon",
      "Bill Clinton",
      "Donald Trump",
    ],
    correctAnswer: "Andrew Johnson",
    difficulty: "intermediate",
    category: "history",
  },
  {
    question: "What was the main purpose of the Magna Carta?",
    options: [
      "To establish a parliament",
      "To limit the power of the king",
      "To create a constitution",
      "To declare independence",
    ],
    correctAnswer: "To limit the power of the king",
    difficulty: "intermediate",
    category: "history",
  },
  {
    question: "Who was the first person to circumnavigate the globe?",
    options: [
      "Ferdinand Magellan",
      "Christopher Columbus",
      "Vasco da Gama",
      "James Cook",
    ],
    correctAnswer: "Ferdinand Magellan",
    difficulty: "intermediate",
    category: "history",
  },
  {
    question:
      "What was the name of the first successful English colony in America?",
    options: ["Jamestown", "Plymouth", "Roanoke", "Salem"],
    correctAnswer: "Jamestown",
    difficulty: "intermediate",
    category: "history",
  },
  {
    question:
      "Who was the first President of the United States to resign from office?",
    options: [
      "Andrew Johnson",
      "Richard Nixon",
      "Bill Clinton",
      "Donald Trump",
    ],
    correctAnswer: "Richard Nixon",
    difficulty: "intermediate",
    category: "history",
  },
  {
    question: "What was the main cause of the French Revolution?",
    options: [
      "Taxation",
      "Religious Disputes",
      "Economic Inequality",
      "Territorial Expansion",
    ],
    correctAnswer: "Economic Inequality",
    difficulty: "intermediate",
    category: "history",
  },
  {
    question: "Who was the first Emperor of China?",
    options: ["Qin Shi Huang", "Liu Bang", "Kublai Khan", "Sun Yat-sen"],
    correctAnswer: "Qin Shi Huang",
    difficulty: "intermediate",
    category: "history",
  },
  {
    question:
      "What was the name of the ship that brought the Pilgrims to America in 1620?",
    options: ["Mayflower", "Santa Maria", "Pinta", "Nina"],
    correctAnswer: "Mayflower",
    difficulty: "easy",
    category: "history",
  },
  {
    question: "Who was the first Emperor of Rome?",
    options: ["Julius Caesar", "Augustus", "Nero", "Caligula"],
    correctAnswer: "Augustus",
    difficulty: "easy",
    category: "history",
  },
  {
    question: "What was the main cause of the American Civil War?",
    options: ["Slavery", "Taxation", "Territorial Expansion", "Trade Disputes"],
    correctAnswer: "Slavery",
    difficulty: "easy",
    category: "history",
  },
  {
    question: "Who was the British Prime Minister during World War II?",
    options: [
      "Winston Churchill",
      "Neville Chamberlain",
      "Clement Attlee",
      "Harold Macmillan",
    ],
    correctAnswer: "Winston Churchill",
    difficulty: "easy",
    category: "history",
  },
  {
    question:
      "What was the name of the first manned mission to land on the moon?",
    options: ["Apollo 11", "Apollo 12", "Apollo 13", "Apollo 14"],
    correctAnswer: "Apollo 11",
    difficulty: "easy",
    category: "history",
  },
  {
    question: "Who was the first female Prime Minister of the United Kingdom?",
    options: [
      "Margaret Thatcher",
      "Theresa May",
      "Angela Merkel",
      "Indira Gandhi",
    ],
    correctAnswer: "Margaret Thatcher",
    difficulty: "easy",
    category: "history",
  },
  {
    question: "In which year did the Berlin Wall fall?",
    options: ["1987", "1988", "1989", "1990"],
    correctAnswer: "1989",
    difficulty: "easy",
    category: "history",
  },
  {
    question:
      "Who was the leader of the Soviet Union during the Cuban Missile Crisis?",
    options: [
      "Joseph Stalin",
      "Nikita Khrushchev",
      "Leonid Brezhnev",
      "Mikhail Gorbachev",
    ],
    correctAnswer: "Nikita Khrushchev",
    difficulty: "intermediate",
    category: "history",
  },
  {
    question: "What was the name of the treaty that ended World War I?",
    options: [
      "Treaty of Versailles",
      "Treaty of Paris",
      "Treaty of Tordesillas",
      "Treaty of Ghent",
    ],
    correctAnswer: "Treaty of Versailles",
    difficulty: "intermediate",
    category: "history",
  },
  {
    question:
      "Who was the first President of the United States to be impeached?",
    options: [
      "Andrew Johnson",
      "Richard Nixon",
      "Bill Clinton",
      "Donald Trump",
    ],
    correctAnswer: "Andrew Johnson",
    difficulty: "intermediate",
    category: "history",
  },
  {
    question: "What was the main purpose of the Magna Carta?",
    options: [
      "To establish a parliament",
      "To limit the power of the king",
      "To create a constitution",
      "To declare independence",
    ],
    correctAnswer: "To limit the power of the king",
    difficulty: "intermediate",
    category: "history",
  },
  // Science
  {
    question: "What is the chemical symbol for water?",
    options: ["H2O", "O2", "CO2", "NaCl"],
    correctAnswer: "H2O",
    difficulty: "easy",
    category: "science",
  },
  {
    question: "What planet is known as the Red Planet?",
    options: ["Earth", "Mars", "Jupiter", "Saturn"],
    correctAnswer: "Mars",
    difficulty: "easy",
    category: "science",
  },
  {
    question: "What is the largest planet in our solar system?",
    options: ["Earth", "Jupiter", "Saturn", "Mars"],
    correctAnswer: "Jupiter",
    difficulty: "easy",
    category: "science",
  },
  {
    question: "What is the process by which plants make their food?",
    options: ["Photosynthesis", "Respiration", "Digestion", "Transpiration"],
    correctAnswer: "Photosynthesis",
    difficulty: "easy",
    category: "science",
  },
  {
    question: "What is the boiling point of water?",
    options: ["90°C", "100°C", "110°C", "120°C"],
    correctAnswer: "100°C",
    difficulty: "easy",
    category: "science",
  },
  {
    question: "What is the chemical symbol for gold?",
    options: ["Au", "Ag", "Pb", "Pt"],
    correctAnswer: "Au",
    difficulty: "easy",
    category: "science",
  },
  {
    question: "What is the speed of light?",
    options: ["300,000 km/s", "150,000 km/s", "450,000 km/s", "600,000 km/s"],
    correctAnswer: "300,000 km/s",
    difficulty: "intermediate",
    category: "science",
  },
  {
    question: "What is the main gas found in the air we breathe?",
    options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"],
    correctAnswer: "Nitrogen",
    difficulty: "intermediate",
    category: "science",
  },
  {
    question: "What is the powerhouse of the cell?",
    options: ["Nucleus", "Mitochondria", "Ribosome", "Chloroplast"],
    correctAnswer: "Mitochondria",
    difficulty: "intermediate",
    category: "science",
  },
  {
    question: "What is the chemical formula for table salt?",
    options: ["NaCl", "KCl", "CaCl2", "MgCl2"],
    correctAnswer: "NaCl",
    difficulty: "intermediate",
    category: "science",
  },
  {
    question: "What is the hardest natural substance on Earth?",
    options: ["Gold", "Iron", "Diamond", "Platinum"],
    correctAnswer: "Diamond",
    difficulty: "easy",
    category: "science",
  },
  {
    question: "What is the most abundant gas in the Earth's atmosphere?",
    options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"],
    correctAnswer: "Nitrogen",
    difficulty: "easy",
    category: "science",
  },
  {
    question: "What is the chemical symbol for iron?",
    options: ["Fe", "Ir", "In", "I"],
    correctAnswer: "Fe",
    difficulty: "easy",
    category: "science",
  },
  {
    question: "What is the chemical formula for carbon dioxide?",
    options: ["CO", "CO2", "C2O", "C2O2"],
    correctAnswer: "CO2",
    difficulty: "easy",
    category: "science",
  },
  {
    question: "What is the process by which a liquid turns into a gas?",
    options: ["Condensation", "Evaporation", "Sublimation", "Deposition"],
    correctAnswer: "Evaporation",
    difficulty: "easy",
    category: "science",
  },
  {
    question: "What is the chemical symbol for sodium?",
    options: ["Na", "S", "N", "Si"],
    correctAnswer: "Na",
    difficulty: "easy",
    category: "science",
  },
  {
    question: "What is the chemical formula for methane?",
    options: ["CH4", "C2H6", "C3H8", "C4H10"],
    correctAnswer: "CH4",
    difficulty: "intermediate",
    category: "science",
  },
  {
    question: "What is the chemical formula for glucose?",
    options: ["C6H12O6", "C6H6O6", "C6H12O12", "C12H6O6"],
    correctAnswer: "C6H12O6",
    difficulty: "intermediate",
    category: "science",
  },
  {
    question: "What is the chemical formula for ammonia?",
    options: ["NH3", "NH4", "NH2", "NH"],
    correctAnswer: "NH3",
    difficulty: "intermediate",
    category: "science",
  },
  {
    question: "What is the chemical formula for sulfuric acid?",
    options: ["H2SO4", "H2SO3", "H2SO2", "H2SO"],
    correctAnswer: "H2SO4",
    difficulty: "intermediate",
    category: "science",
  },
  {
    question: "What is the chemical formula for hydrochloric acid?",
    options: ["HCl", "H2Cl", "HCl2", "H2Cl2"],
    correctAnswer: "HCl",
    difficulty: "intermediate",
    category: "science",
  },
  {
    question: "What is the chemical formula for nitric acid?",
    options: ["HNO3", "HNO2", "HNO", "H2NO3"],
    correctAnswer: "HNO3",
    difficulty: "intermediate",
    category: "science",
  },
  {
    question: "What is the chemical formula for acetic acid?",
    options: ["CH3COOH", "C2H4O2", "C2H6O2", "C2H2O2"],
    correctAnswer: "CH3COOH",
    difficulty: "intermediate",
    category: "science",
  },
  {
    question: "What is the chemical formula for ethanol?",
    options: ["C2H5OH", "C2H6OH", "C2H4OH", "C2H3OH"],
    correctAnswer: "C2H5OH",
    difficulty: "intermediate",
    category: "science",
  },
  {
    question: "What is the chemical formula for benzene?",
    options: ["C6H6", "C6H12", "C6H10", "C6H8"],
    correctAnswer: "C6H6",
    difficulty: "intermediate",
    category: "science",
  },
  {
    question: "What is the chemical formula for toluene?",
    options: ["C7H8", "C7H10", "C7H12", "C7H14"],
    correctAnswer: "C7H8",
    difficulty: "intermediate",
    category: "science",
  },
  {
    question: "What is the chemical formula for acetone?",
    options: ["C3H6O", "C3H8O", "C3H4O", "C3H2O"],
    correctAnswer: "C3H6O",
    difficulty: "intermediate",
    category: "science",
  },
  {
    question: "What is the chemical formula for formaldehyde?",
    options: ["CH2O", "CH4O", "CH3O", "CH5O"],
    correctAnswer: "CH2O",
    difficulty: "intermediate",
    category: "science",
  },
  {
    question: "What is the chemical formula for hydrogen peroxide?",
    options: ["H2O2", "H2O", "H2O3", "H2O4"],
    correctAnswer: "H2O2",
    difficulty: "intermediate",
    category: "science",
  },
  {
    question: "What is the chemical formula for sodium chloride?",
    options: ["NaCl", "NaCl2", "NaCl3", "NaCl4"],
    correctAnswer: "NaCl",
    difficulty: "intermediate",
    category: "science",
  },
  // Geography
  {
    question: "What is the capital of France?",
    options: ["Berlin", "Madrid", "Paris", "Rome"],
    correctAnswer: "Paris",
    difficulty: "easy",
    category: "geography",
  },
  {
    question: "Which continent is known as the 'Dark Continent'?",
    options: ["Asia", "Africa", "Europe", "Australia"],
    correctAnswer: "Africa",
    difficulty: "easy",
    category: "geography",
  },
  {
    question: "What is the largest ocean on Earth?",
    options: [
      "Atlantic Ocean",
      "Indian Ocean",
      "Arctic Ocean",
      "Pacific Ocean",
    ],
    correctAnswer: "Pacific Ocean",
    difficulty: "easy",
    category: "geography",
  },
  {
    question: "What is the longest river in the world?",
    options: [
      "Amazon River",
      "Nile River",
      "Yangtze River",
      "Mississippi River",
    ],
    correctAnswer: "Nile River",
    difficulty: "easy",
    category: "geography",
  },
  {
    question: "What is the smallest country in the world?",
    options: ["Monaco", "Vatican City", "San Marino", "Liechtenstein"],
    correctAnswer: "Vatican City",
    difficulty: "easy",
    category: "geography",
  },
  {
    question: "What is the capital of Japan?",
    options: ["Beijing", "Seoul", "Tokyo", "Bangkok"],
    correctAnswer: "Tokyo",
    difficulty: "easy",
    category: "geography",
  },
  {
    question: "Which country is known as the Land of the Rising Sun?",
    options: ["India", "Australia", "Japan", "South Korea"],
    correctAnswer: "Japan",
    difficulty: "easy",
    category: "geography",
  },
  {
    question: "What is the highest mountain in the world?",
    options: ["K2", "Kangchenjunga", "Mount Everest", "Lhotse"],
    correctAnswer: "Mount Everest",
    difficulty: "easy",
    category: "geography",
  },
  {
    question: "What is the capital of Australia?",
    options: ["Sydney", "Melbourne", "Canberra", "Brisbane"],
    correctAnswer: "Canberra",
    difficulty: "easy",
    category: "geography",
  },
  {
    question: "What is the largest desert in the world?",
    options: [
      "Sahara Desert",
      "Arabian Desert",
      "Gobi Desert",
      "Antarctic Desert",
    ],
    correctAnswer: "Antarctic Desert",
    difficulty: "intermediate",
    category: "geography",
  },
  {
    question: "What is the capital of Canada?",
    options: ["Toronto", "Vancouver", "Ottawa", "Montreal"],
    correctAnswer: "Ottawa",
    difficulty: "easy",
    category: "geography",
  },
  {
    question: "Which country has the most natural lakes?",
    options: ["Canada", "Russia", "United States", "Brazil"],
    correctAnswer: "Canada",
    difficulty: "intermediate",
    category: "geography",
  },
  {
    question: "What is the capital of Brazil?",
    options: ["Rio de Janeiro", "São Paulo", "Brasília", "Salvador"],
    correctAnswer: "Brasília",
    difficulty: "easy",
    category: "geography",
  },
  {
    question: "What is the longest river in South America?",
    options: [
      "Amazon River",
      "Paraná River",
      "Orinoco River",
      "São Francisco River",
    ],
    correctAnswer: "Amazon River",
    difficulty: "easy",
    category: "geography",
  },
  {
    question: "What is the capital of Egypt?",
    options: ["Cairo", "Alexandria", "Giza", "Luxor"],
    correctAnswer: "Cairo",
    difficulty: "easy",
    category: "geography",
  },
  {
    question: "Which country is the largest by land area?",
    options: ["Canada", "China", "Russia", "United States"],
    correctAnswer: "Russia",
    difficulty: "easy",
    category: "geography",
  },
  {
    question: "What is the capital of India?",
    options: ["Mumbai", "New Delhi", "Bangalore", "Kolkata"],
    correctAnswer: "New Delhi",
    difficulty: "easy",
    category: "geography",
  },
  {
    question: "What is the capital of Italy?",
    options: ["Venice", "Milan", "Rome", "Florence"],
    correctAnswer: "Rome",
    difficulty: "easy",
    category: "geography",
  },
  {
    question: "What is the capital of Germany?",
    options: ["Berlin", "Munich", "Frankfurt", "Hamburg"],
    correctAnswer: "Berlin",
    difficulty: "easy",
    category: "geography",
  },
  {
    question: "What is the capital of Spain?",
    options: ["Barcelona", "Madrid", "Seville", "Valencia"],
    correctAnswer: "Madrid",
    difficulty: "easy",
    category: "geography",
  },
  {
    question: "What is the capital of Russia?",
    options: ["Moscow", "Saint Petersburg", "Novosibirsk", "Yekaterinburg"],
    correctAnswer: "Moscow",
    difficulty: "easy",
    category: "geography",
  },
  {
    question: "What is the capital of China?",
    options: ["Shanghai", "Beijing", "Guangzhou", "Shenzhen"],
    correctAnswer: "Beijing",
    difficulty: "easy",
    category: "geography",
  },
  {
    question: "What is the capital of South Korea?",
    options: ["Seoul", "Busan", "Incheon", "Daegu"],
    correctAnswer: "Seoul",
    difficulty: "easy",
    category: "geography",
  },
  {
    question: "What is the capital of Mexico?",
    options: ["Guadalajara", "Monterrey", "Mexico City", "Tijuana"],
    correctAnswer: "Mexico City",
    difficulty: "easy",
    category: "geography",
  },
  {
    question: "What is the capital of Argentina?",
    options: ["Buenos Aires", "Córdoba", "Rosario", "Mendoza"],
    correctAnswer: "Buenos Aires",
    difficulty: "easy",
    category: "geography",
  },
  {
    question: "What is the capital of South Africa?",
    options: ["Johannesburg", "Cape Town", "Pretoria", "Durban"],
    correctAnswer: "Pretoria",
    difficulty: "easy",
    category: "geography",
  },
  {
    question: "What is the capital of Saudi Arabia?",
    options: ["Jeddah", "Mecca", "Medina", "Riyadh"],
    correctAnswer: "Riyadh",
    difficulty: "easy",
    category: "geography",
  },
  {
    question: "What is the capital of Turkey?",
    options: ["Istanbul", "Ankara", "Izmir", "Antalya"],
    correctAnswer: "Ankara",
    difficulty: "easy",
    category: "geography",
  },
  {
    question: "What is the capital of Thailand?",
    options: ["Bangkok", "Phuket", "Chiang Mai", "Pattaya"],
    correctAnswer: "Bangkok",
    difficulty: "easy",
    category: "geography",
  },
  {
    question: "What is the capital of the United Kingdom?",
    options: ["London", "Edinburgh", "Manchester", "Birmingham"],
    correctAnswer: "London",
    difficulty: "easy",
    category: "geography",
  },
  // Technology
  {
    question: "Which programming language is known as the language of the web?",
    options: ["Python", "JavaScript", "C++", "Java"],
    correctAnswer: "JavaScript",
    difficulty: "easy",
    category: "technology",
  },
  {
    question: "What does HTML stand for?",
    options: [
      "HyperText Markup Language",
      "HyperText Machine Language",
      "HyperText and links Markup Language",
      "HyperTool Markup Language",
    ],
    correctAnswer: "HyperText Markup Language",
    difficulty: "easy",
    category: "technology",
  },
  {
    question: "What is the main function of a web browser?",
    options: [
      "To compile code",
      "To browse the internet",
      "To edit photos",
      "To play music",
    ],
    correctAnswer: "To browse the internet",
    difficulty: "easy",
    category: "technology",
  },
  {
    question: "What does CSS stand for?",
    options: [
      "Cascading Style Sheets",
      "Computer Style Sheets",
      "Creative Style Sheets",
      "Colorful Style Sheets",
    ],
    correctAnswer: "Cascading Style Sheets",
    difficulty: "easy",
    category: "technology",
  },
  {
    question:
      "What is the name of the first electronic general-purpose computer?",
    options: ["ENIAC", "UNIVAC", "IBM PC", "Apple I"],
    correctAnswer: "ENIAC",
    difficulty: "easy",
    category: "technology",
  },
  {
    question: "What is the primary purpose of an operating system?",
    options: [
      "To manage hardware and software resources",
      "To create documents",
      "To browse the internet",
      "To play games",
    ],
    correctAnswer: "To manage hardware and software resources",
    difficulty: "easy",
    category: "technology",
  },
  {
    question: "What does HTTP stand for?",
    options: [
      "HyperText Transfer Protocol",
      "HyperText Transmission Protocol",
      "HyperText Transfer Program",
      "HyperText Transmission Program",
    ],
    correctAnswer: "HyperText Transfer Protocol",
    difficulty: "easy",
    category: "technology",
  },
  {
    question: "What is the name of the first web browser?",
    options: ["Mosaic", "Netscape", "Internet Explorer", "WorldWideWeb"],
    correctAnswer: "WorldWideWeb",
    difficulty: "intermediate",
    category: "technology",
  },
  {
    question: "What is the main purpose of a firewall?",
    options: [
      "To protect against unauthorized access",
      "To speed up internet connection",
      "To store data",
      "To create backups",
    ],
    correctAnswer: "To protect against unauthorized access",
    difficulty: "intermediate",
    category: "technology",
  },
  {
    question: "What does SQL stand for?",
    options: [
      "Structured Query Language",
      "Structured Question Language",
      "Simple Query Language",
      "Simple Question Language",
    ],
    correctAnswer: "Structured Query Language",
    difficulty: "intermediate",
    category: "technology",
  },
  {
    question: "What is the main function of a database?",
    options: [
      "To store and manage data",
      "To create websites",
      "To edit videos",
      "To play music",
    ],
    correctAnswer: "To store and manage data",
    difficulty: "intermediate",
    category: "technology",
  },
  {
    question: "What is the name of the first programming language?",
    options: ["FORTRAN", "COBOL", "BASIC", "Assembly"],
    correctAnswer: "FORTRAN",
    difficulty: "intermediate",
    category: "technology",
  },
  {
    question: "What is the main purpose of an API?",
    options: [
      "To allow different software applications to communicate",
      "To create graphics",
      "To edit photos",
      "To play music",
    ],
    correctAnswer: "To allow different software applications to communicate",
    difficulty: "intermediate",
    category: "technology",
  },
  {
    question: "What does GPU stand for?",
    options: [
      "Graphics Processing Unit",
      "General Processing Unit",
      "Graphics Performance Unit",
      "General Performance Unit",
    ],
    correctAnswer: "Graphics Processing Unit",
    difficulty: "intermediate",
    category: "technology",
  },
  {
    question: "What is the main purpose of a compiler?",
    options: [
      "To translate source code into machine code",
      "To create documents",
      "To browse the internet",
      "To play games",
    ],
    correctAnswer: "To translate source code into machine code",
    difficulty: "intermediate",
    category: "technology",
  },
  {
    question:
      "What is the name of the first commercially successful personal computer?",
    options: ["Apple II", "IBM PC", "Commodore 64", "Atari 800"],
    correctAnswer: "Apple II",
    difficulty: "intermediate",
    category: "technology",
  },
  {
    question: "What does RAM stand for?",
    options: [
      "Random Access Memory",
      "Read Access Memory",
      "Readily Available Memory",
      "Randomly Available Memory",
    ],
    correctAnswer: "Random Access Memory",
    difficulty: "easy",
    category: "technology",
  },
  {
    question: "What is the main purpose of a router?",
    options: [
      "To direct network traffic",
      "To store data",
      "To create backups",
      "To edit photos",
    ],
    correctAnswer: "To direct network traffic",
    difficulty: "intermediate",
    category: "technology",
  },
  {
    question: "What is the name of the first search engine?",
    options: ["Archie", "Google", "Yahoo", "AltaVista"],
    correctAnswer: "Archie",
    difficulty: "intermediate",
    category: "technology",
  },
  {
    question: "What is the main purpose of a VPN?",
    options: [
      "To create a secure connection over the internet",
      "To speed up internet connection",
      "To store data",
      "To create backups",
    ],
    correctAnswer: "To create a secure connection over the internet",
    difficulty: "intermediate",
    category: "technology",
  },
  {
    question: "What does IoT stand for?",
    options: [
      "Internet of Things",
      "Internet of Technology",
      "Internet of Tools",
      "Internet of Transactions",
    ],
    correctAnswer: "Internet of Things",
    difficulty: "intermediate",
    category: "technology",
  },
  {
    question: "What is the main purpose of a blockchain?",
    options: [
      "To securely record transactions",
      "To create websites",
      "To edit videos",
      "To play music",
    ],
    correctAnswer: "To securely record transactions",
    difficulty: "intermediate",
    category: "technology",
  },
  {
    question: "What is the name of the first smartphone?",
    options: ["IBM Simon", "iPhone", "BlackBerry", "Nokia 9000"],
    correctAnswer: "IBM Simon",
    difficulty: "intermediate",
    category: "technology",
  },
  {
    question: "What does AI stand for?",
    options: [
      "Artificial Intelligence",
      "Automated Intelligence",
      "Advanced Intelligence",
      "Augmented Intelligence",
    ],
    correctAnswer: "Artificial Intelligence",
    difficulty: "easy",
    category: "technology",
  },
  {
    question: "What is the main purpose of a QR code?",
    options: [
      "To store information that can be scanned",
      "To create documents",
      "To browse the internet",
      "To play games",
    ],
    correctAnswer: "To store information that can be scanned",
    difficulty: "easy",
    category: "technology",
  },
  {
    question: "What does URL stand for?",
    options: [
      "Uniform Resource Locator",
      "Universal Resource Locator",
      "Uniform Resource Link",
      "Universal Resource Link",
    ],
    correctAnswer: "Uniform Resource Locator",
    difficulty: "easy",
    category: "technology",
  },
  {
    question: "What is the main purpose of a CAPTCHA?",
    options: [
      "To distinguish between humans and bots",
      "To speed up internet connection",
      "To store data",
      "To create backups",
    ],
    correctAnswer: "To distinguish between humans and bots",
    difficulty: "intermediate",
    category: "technology",
  },
  {
    question: "What is the name of the first social media platform?",
    options: ["Six Degrees", "Facebook", "MySpace", "Friendster"],
    correctAnswer: "Six Degrees",
    difficulty: "intermediate",
    category: "technology",
  },
  {
    question: "What is the main purpose of a DNS server?",
    options: [
      "To translate domain names into IP addresses",
      "To create websites",
      "To edit videos",
      "To play music",
    ],
    correctAnswer: "To translate domain names into IP addresses",
    difficulty: "intermediate",
    category: "technology",
  },
  {
    question: "What does SSL stand for?",
    options: [
      "Secure Sockets Layer",
      "Secure Software Layer",
      "Secure Sockets Link",
      "Secure Software Link",
    ],
    correctAnswer: "Secure Sockets Layer",
    difficulty: "intermediate",
    category: "technology",
  },
];

export default quizData;
